// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvxqshwznfgvtchfhdko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2eHFzaHd6bmZndnRjaGZoZGtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTMzODQsImV4cCI6MjA2MzkyOTM4NH0.ljA04UQRGwZEMfxS8TMM-6GuQEplk6DWQe8fUntiuyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);